version: '3.1'

services:
  discovery-server:
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    expose:
      - 8081
    networks:
      - dev
    restart: on-failure  
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    links:
      - discovery-server:discovery  
    environment:
      DISCOVERY_URL: http://discovery:8081/eureka
    ports:
      - "8082:8082"
    expose:
      - 8082
    depends_on:
      - discovery-server
      - pagamentos
      - avaliacao
      - pedidos
    networks:
      - dev
    restart: on-failure  
  pagamentos:
    build:
      context: ./pagamentos
      dockerfile: Dockerfile
    links:
      - database-pagamentos:mysqldb
      - discovery-server:discovery
      - rabbitmq:rabbit  
    environment:
      MYSQL_URL: jdbc:mysql://mysqldb:3306/pagamentos?createDatabaseIfNotExist=true
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      DISCOVERY_URL: http://discovery:8081/eureka
      RABBIT_HOST: rabbit
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    depends_on:
      - database-pagamentos
      - rabbitmq
      - discovery-server
    networks:
      - dev
    volumes:
      - mysql-data:/var/lib/mysql  
    restart: on-failure  
  avaliacao:
    build:
      context: ./avaliacao
      dockerfile: Dockerfile
    links:
      - discovery-server:discovery
      - rabbitmq:rabbit  
    environment:
      DISCOVERY_URL: http://discovery:8081/eureka
      RABBIT_HOST: rabbit
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    depends_on:
      - rabbitmq
      - discovery-server
    networks:
      - dev
    restart: on-failure  
  pedidos:
    build:
      context: ./pedidos
      dockerfile: Dockerfile
    links:
      - database-pedidos:postgresdb
      - discovery-server:discovery  
      - rabbitmq:rabbit
    environment:
      POSTGRES_URL: jdbc:postgresql://postgresdb:5432/pedidos?createDatabaseIfNotExist=true
      DB_USER: postgres
      DB_PASSWORD: postgres
      DISCOVERY_URL: http://discovery:8081/eureka
      RABBIT_HOST: rabbit
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    depends_on:
      - database-pedidos
      - rabbitmq
      - discovery-server
    networks:
      - dev
    volumes:
      - postgres-data:/var/lib/postgresql/data  
    restart: on-failure
  database-pagamentos:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    expose:
      - 3306  
    environment:
      MYSQL_DATABASE: pagamentos
      MYSQL_ROOT_PASSWORD: password
    networks:
      - dev
  database-pedidos:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pedidos
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - dev  
    
  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 5672
      - 15672  
    volumes:
      - ./dados:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - dev

networks:
  dev:
    driver: bridge
volumes:
  mysql-data:
  postgres-data:    