# docker-compose.yml

version: '3.8'

services:
  avaliacao:
    build: ./avaliacao
    ports:
      - "0:0"
    depends_on:
      - rabbitmq
    networks:
      - ifbafood-network

  discovery-server:
    build: ./discovery-server
    ports:
      - "8081:8081"
    networks:
      - ifbafood-network

  gateway:
    build: ./gateway
    ports:
      - "8082:8082"
    depends_on:
      - discovery-server
    networks:
      - ifbafood-network

  pagamentos:
    build: ./pagamentos
    ports:
      - "0:0"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/ifbafood-pagamento?createDatabaseIfNotExist=true
    depends_on:
      - rabbitmq
      - db
      - discovery-server
    networks:
      - ifbafood-network

  pedidos:
    build: ./pedidos
    ports:
      - "0:0"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/ifbafood-pedidos?createDatabaseIfNotExist=true
    depends_on:
      - rabbitmq
      - db
      - discovery-server
    networks:
      - ifbafood-network

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=ativ$webmb
    networks:
      - ifbafood-network

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=ativ$webmb
      - MYSQL_DATABASE=ifbafood
      - MYSQL_USER=root
      - MYSQL_PASSWORD=ativ$webmb
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ifbafood-network

networks:
  ifbafood-network:
    driver: bridge

volumes:
  mysql-data:
